### ISSUE TITLE
thank you - secrets.<username>_TOKEN

### ISSUE THREAD

**Issue by pkrasam** [simonw/simonw#3]
@simonw thanks for sharing this feature -- I set it up today and I think it is failing in one step in `build.yml`

I can't remember what this section does?
```
    - name: Update README
      env:
        PKRASAM_TOKEN: ${{ secrets.PKRASAM_TOKEN }}
```

**Comment by simonw** [comment]
You need a GitHub personal access token in order to access the GitHub GraphQL API. You can create that here: https://github.com/settings/tokens/new

Then create a secret in your repo settings with it.
